### ISSUE TITLE
Small typo in the example execution

### ISSUE THREAD

**Issue by bcamel** [aalepere/luigi_spark_flask_cicd#1]
I think, the pipeline should be `Model` rather than `Transform` (in [README.MD](https://github.com/aalepere/luigi_spark_flask_cicd/blob/master/README.md))

```
PYTHONPATH='.' luigi --module pipeline Model --local-scheduler --input-file "../source_data/titanic.csv" --output-path "data_out"
```

**Comment by aalepere** [comment]
Yes true! thanks if you want to run the full pipeline 👍

**Comment by aalepere** [comment]
`README` updated.
